# Additional resources

There are a number of incredible open-access online resources that, using the skills you have developed in this tutorial, will allow you to start adapting your figures and plots to make them as informative as possible for your reader. Additionally, there are also many excellent resources that expand on some of the topics we have covered here briefly, particularly data wrangling, that can help you consolidate and expand your skill set.

**PsyTeachR**

The [psyTeachR](https://psyteachr.github.io/) team at the University of Glasgow School of Psychology and Neuroscience has successfully made the transition to teaching reproducible research using R across all undergraduate and postgraduate levels. Our curriculum now emphasizes essential ‘data science’ graduate skills that have been overlooked in traditional approaches to teaching, including programming skills, data visualisation, data wrangling and reproducible reports. Students learn about probability and inference through data simulation as well as by working with real datasets. These materials cover all the functions we have used in this tutorial in more depth and all have Creative Commons licences to allow their use and reuse without attribution.

* [Applied Data Skills](https://psyteachr.github.io/ads/)
* [Level 1 Data Skills](https://psyteachr.github.io/data-skills/)
* [Level 2 Analyses](https://psyteachr.github.io/analysis/)
* [Level 3 Statistical Models](https://psyteachr.github.io/stat-models/)
* [Msc Fundamentals of Quantititive Analysis](https://psyteachr.github.io/fun-quant/)
* [MSc Data Skills for Reproducible Research](https://psyteachr.github.io/reprores/)

**Installing R and RStudio**

* [Installing R - PsyTeachR](https://psyteachr.github.io/data-skills-v1/installing-r.html)
* [Running R on your own computer (walkthrough videos) - Danielle Navarro](https://www.youtube.com/playlist?list=PLRPB0ZzEYegOZivdelOuEn-R-XUN-DOjd)

**Intro to R and RStudio**

* RStudio Essentials: [Programming - Part 1 (Writing code in RStudio)](https://www.rstudio.com/resources/webinars/programming-part-1-writing-code-in-rstudio/)
* RStudio Essentials: [Programming - Part 2 (Debugging code in RStudio)](https://www.rstudio.com/resources/webinars/programming-part-2-debugging-code-in-rstudio/) 

**R Markdown**

* [Introduction to R Markdown](https://rmarkdown.rstudio.com/lesson-1.html)
* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)

**Data wrangling**

* [R for Data Science](https://r4ds.had.co.nz/)
* [Text Mining with R](https://www.tidytextmining.com/)

**Data visualisation**

* [R Graph Gallery](https://www.r-graph-gallery.com/)
* [Fundamentals of Data Vizualisation](https://clauswilke.com/dataviz/)
* [Data Vizualisation: A Practical Introduction](https://socviz.co/)
* [Look at Data](https://socviz.co/lookatdata.html) from [Data Vizualization for Social Science](http://socviz.co/)
* [Graphs](http://www.cookbook-r.com/Graphs) in *Cookbook for R*
* [Top 50 ggplot2 Visualizations](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
* [R Graphics Cookbook](http://www.cookbook-r.com/Graphs/) by Winston Chang
* [ggplot extensions](https://exts.ggplot2.tidyverse.org/)
* [plotly](https://plot.ly/ggplot2/) for creating interactive graphs
* [Drawing Beautiful Maps Programmatically](https://r-spatial.org/r/2018/10/25/ggplot2-sf.html)
* [gganimate](https://gganimate.com/)

